-- Create the scans table
create table public.scans (
  id bigint generated by default as identity primary key,
  group_id text not null,
  invasive_level int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional, but good practice, though we are using Service Role key so it bypasses)
alter table public.scans enable row level security;

-- Policy to allow anonymous/service role to insert and read (simplified for this demo)
-- Since we use the service role key in the backend, we technically bypass RLS,
-- but if we used the anon key, we'd need policies.
create policy "Enable read access for all users" on public.scans for select using (true);
create policy "Enable insert access for all users" on public.scans for insert with check (true);

-- Added for Gallery feature:
-- Run this in your Supabase SQL editor to support storing images:
-- ALTER TABLE public.scans ADD COLUMN image_path text;

-- Added for Reference Map Star targeting:
-- ALTER TABLE public.scans ADD COLUMN removal_difficulty int DEFAULT 50;
